### ISSUE TITLE
Notification Numbers in Light Themes

### ISSUE THREAD

**Issue by Mioni** [An-dz/ScriptJaeger#13]
Can you improve this? 
![b6084b88-baa9-48d2-ac62-dc86f34f7665](https://user-images.githubusercontent.com/6830783/40571451-63a0011e-606f-11e8-8fd9-89609285a271.png)

Another thing what's the difference for Umatrix? Is there a difference?
Thank you!

**Comment by An-dz** [comment]
Done.

There are 2 main differences from uMatrix:

1. uMatrix blocks more stuff, like images and css.\
ScriptJäger only blocks frames, scripts and websocket.
2. uMatrix uses blacklists to block stuff.\
ScriptJäger don't, it uses a simple algorithm that decides if the resource domain looks trustworthy or not depending on the [policy defined](https://github.com/An-dz/ScriptJaeger/wiki/User:-The-Popup-Interface#policy).
